name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: .
          args: |
            test --summary all
            build --summary all
          working-directory: example
        env:
          ZIG_VERSION: 0.11.0
      - name: Run Dagger Pipelines
        run: dagger run deno run -A ../src/dagger/runner.ts
        working-directory: example
